DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGINT auto_increment PRIMARY KEY, NAME VARCHAR(255), SURNAME VARCHAR(255), FATHER_NAME VARCHAR(255), DATE_OF_BIRTH VARCHAR(255));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID BIGINT auto_increment PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID BIGINT auto_increment PRIMARY KEY, TITLE VARCHAR(255), NUMBER_OF_PAGES INT, YEAR_OF_PUBLISHING INT,
       AUTHOR_ID BIGINT, GENRE_ID BIGINT);

ALTER TABLE BOOK ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID);
ALTER TABLE BOOK ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID);

