DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGINT auto_increment PRIMARY KEY, NAME VARCHAR(255), SURNAME VARCHAR(255), FATHER_NAME VARCHAR(255),
DATE_OF_BIRTH VARCHAR(255));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID BIGINT auto_increment PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID BIGINT auto_increment PRIMARY KEY, TITLE VARCHAR(255), NUMBER_OF_PAGES INT, YEAR_OF_PUBLISHING INT,
       GENRE_ID BIGINT);

DROP TABLE IF EXISTS BOOK_COMMENT;
CREATE TABLE BOOK_COMMENT(ID BIGINT auto_increment PRIMARY KEY, TITLE VARCHAR(255), TEXT_ VARCHAR(255), BOOK BIGINT);

DROP TABLE IF EXISTS BOOK_AUTHOR;
CREATE TABLE BOOK_AUTHOR(ID BIGINT auto_increment PRIMARY KEY, BOOK_ID BIGINT, AUTHOR_ID BIGINT);

ALTER TABLE BOOK ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID);
ALTER TABLE BOOK_AUTHOR ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID);
ALTER TABLE BOOK_AUTHOR ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID);
ALTER TABLE BOOK_COMMENT ADD FOREIGN KEY (BOOK) REFERENCES BOOK(ID);